Default: &defaults
  user: docker
  password: docker
  host: db
  port: 5432
  database: vmxmiddle
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: middle_test
  <<: *defaults

Staging:
  database: middle_staging
  poolsize: 100
  <<: *defaults

Production:
  database: middle_production
  poolsize: 100
  <<: *defaults
