Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: Copyright vision.ai, LLC 2013-2015
  wwwdir: "/Applications/VMX.app/Contents/MacOS/assets/"
  vmxpath: "/Users/tomasz/projects/VMXserver/build/VMXserver.app/Contents/MacOS/"
  #vmxpath: "/Applications/VMX.app/Contents/MacOS/VMXserver.app/Contents/MacOS/"
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
